### ISSUE TITLE
ทำหน้าเลือกตัวละคร

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/cpe103-test-group-15#17]

**Comment by bambiiisadeer** [comment]
![Uploading 76242BBE-5713-4889-B552-572407C1537A.jpeg…]()

**Comment by bambiiisadeer** [comment]
![781BC232-BD3F-4A12-90B4-6EBA029112E6](https://user-images.githubusercontent.com/110961766/190862358-fc52dc4b-22bb-48e2-831a-2d4f95f66587.jpeg)
![C0AD4359-C2C9-4A56-9911-8F42F8EB3488](https://user-images.githubusercontent.com/110961766/190862362-4fb1adcd-1b2b-465e-a4c2-ef4267f453fb.png)
![A9574890-BE69-49F2-8252-8926B05DC684](https://user-images.githubusercontent.com/110961766/190862364-14f13748-c3a9-4a02-bf2a-725664723309.png)
![BB5755C3-3FB8-41DC-9760-C2EF47102299](https://user-images.githubusercontent.com/110961766/190862368-6ca38788-ce78-4233-ab32-6842eabb98ac.png)
![D2A03055-0DBF-4C15-8C61-C9F49167B55F](https://user-images.githubusercontent.com/110961766/190862371-9466f758-7606-4a90-b6af-5d2e2d496114.png)
![438A63EA-982A-4075-8344-0C6F57A78C4A](https://user-images.githubusercontent.com/110961766/190862375-55d050c9-9718-41e0-aa5a-75a8c7dc92ac.png)

**Comment by bambiiisadeer** [comment]
https://drive.google.com/drive/folders/1-onsqwe_5-BpxpFLAOZCE6ikvbMJ_yAq

**Comment by bambiiisadeer** [comment]
![80305436-6468-461D-AA75-CCF3EBA8C199](https://user-images.githubusercontent.com/110961766/190862782-e5d74f1f-b725-488a-bbe9-113fbc4cf0bf.png)
![97776DAE-67EC-49AA-8093-807784097CFD](https://user-images.githubusercontent.com/110961766/190862789-69bd8454-8eb9-422c-ba95-437611a5b7b2.png)
![B7A2ABBF-754B-4F46-83D5-5FFD5C5F4DEE](https://user-images.githubusercontent.com/110961766/190862791-d4d47c2c-3365-4b26-8ac8-9e058eed9f61.png)
