### ISSUE TITLE
หน้าเปิดเกม/หน้าเมนู

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/cpe103-test-group-15#19]
ดีไซต์/โปรแกรม

**Comment by bambiiisadeer** [comment]
![A0C0F05C-C70B-4AB4-891A-006ADBE1A5CE](https://user-images.githubusercontent.com/110961766/190602812-568c8bf7-1f18-446d-a4b9-a42e4df9ec08.jpeg)
![0A0DA49C-6CCD-4057-8463-0AD90090AF79](https://user-images.githubusercontent.com/110961766/190603263-23246c2d-9648-4c00-b40c-d55ec55b60ee.png)
![1AB216CC-DAB5-40A1-8301-AE96E88D6585](https://user-images.githubusercontent.com/110961766/190603303-fc001166-6637-4813-84ef-ff5d76c50c3e.png)
![78F62E4B-7A0B-4B47-B683-6CD6D7C64EDE](https://user-images.githubusercontent.com/110961766/190603316-468a4ab4-32b3-47c9-a6b7-792322761e3a.gif)
![5088CB19-42E8-4C96-A1F4-20294C4497F3](https://user-images.githubusercontent.com/110961766/190603349-a3cff363-967a-4914-8d8d-467c47809264.gif)

**Comment by bbambiiisadeer** [comment]
![Uploading E1353D43-6D82-4D10-AD56-BDA4C074E7F4.jpeg…]()

**Comment by bambiiisadeer** [comment]
![FADF5CA0-5005-47D9-A806-003572317791](https://user-images.githubusercontent.com/110961766/190603727-484504aa-12e0-4167-9f55-596c580ee4d7.png)

**Comment by bambiiisadeer** [comment]
https://drive.google.com/drive/folders/1-bqkV_jXp3R0oFR0hBcSGkTTQiOULdpa

**Comment by MindIssawara** [comment]
https://scratch.mit.edu/projects/732800594
