### ISSUE TITLE
เรามาตั้งชื่อน้องกันเถอะ

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/cpe103-test-group-15#21]
1.น้องแดง
2.น้องลาวา
3.น้องหนวด
4.น้องเขียว
5.น้องสาว

ใครคิดชื่อไรออกพิมพ์เลขตามด้วยชื่อเลย

**Comment by MindIssawara** [comment]
2. แมก (แมกม่า)
3. โรเจอร์(?)
5. ลิซ่า(?)

**Comment by XSeeGuZ** [comment]
1. Chili
2. Hot Stone
3. Robert
4. Smart
5. Pinky

**Comment by MindIssawara** [comment]
![IMG_0609](https://user-images.githubusercontent.com/110963945/190864118-5fd4189e-bb27-4e6f-a015-0f69241898e7.JPG)
