### ISSUE TITLE
ปก

### ISSUE THREAD

**Issue by bambiiisadeer** [MindIssawara/cpe103-test-group-15#22]
![183AFF9D-0D87-41E6-9C46-8AD2322C9577](https://user-images.githubusercontent.com/110961766/190100010-7c516a14-4219-4e86-ad71-d1968223e62e.gif)

**Comment by bbambiiisadeer** [comment]
![Uploading C68AF118-1B37-4627-9D08-63BD3AC161A1.png…]()

**Comment by bambiiisadeer** [comment]
![AFB00D26-F6D0-4FB7-9BD9-90178A2FE510](https://user-images.githubusercontent.com/110961766/190107880-e3d0d3ad-e452-455f-85fb-4b9f261c76f7.png)
![24F229FA-BFC3-4E40-BA0F-FF784159FA8E](https://user-images.githubusercontent.com/110961766/190107923-1e052e1c-5203-4975-940d-668eeeb9d01b.png)
![FD2F2C0C-E7BA-4F42-A348-1936DA1579D1](https://user-images.githubusercontent.com/110961766/190107930-b52837d1-00be-4c69-9d9d-2d5baa742c77.png)

**Comment by bambiiisadeer** [comment]
![57D3DDD3-063D-4DD8-83C8-74DDCAA59E19](https://user-images.githubusercontent.com/110961766/190108641-400dbca7-b3d5-40f3-8489-990e3614867b.png)

**Comment by bambiiisadeer** [comment]
![ECCBB54E-B62F-4986-A6FC-3C3F08553AA8](https://user-images.githubusercontent.com/110961766/190167023-95f9893d-6b1c-465c-9aaf-ffa33724db86.gif)

**Comment by bbambiiisadeer** [comment]
)
