### ISSUE TITLE
รวมไฟล์เกม

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/cpe103-test-group-15#24]

**Comment by MindIssawara** [comment]
รวมหน้าเมนู
https://scratch.mit.edu/projects/732800594

**Comment by MindIssawara** [comment]
รวมเลือกตัวละคร
https://scratch.mit.edu/projects/733302567

**Comment by Lolorpof** [comment]
**ทั้งหมดก่อนหน้านี้ + แก้บัคฝนคำตอบ**
https://scratch.mit.edu/projects/733317948

**Comment by MindIssawara** [comment]
รวมหน้าจบ+ด่านโบนัส
https://scratch.mit.edu/projects/734314012

**Comment by Lolorpof** [comment]
**เสร็จละ(มีบัค)**
https://scratch.mit.edu/projects/734440389
