### ISSUE TITLE
ศึกษาระบบฟิสิกส์

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/cpe103-test-group-15#4]
ดูจากโปรเจคscratch จากตามเน็ตก็ได้เห็นมีให้ศึกษาอยู่ แล้วก็มีในไลน์ที่เราแปะลิงค์ไว้ให้

**Comment by XSeeGuZ** [comment]
ลองเขียน code Gravity [](https://scratch.mit.edu/projects/729019098/editor)

**Comment by XSeeGuZ** [comment]
ลองเขียน code Gravity
https://scratch.mit.edu/projects/729019098/editor

**Comment by Lolorpof** [comment]
**_Ref - Youtube ฟิสิกส์ลูกบอล_**
https://www.youtube.com/watch?v=Ge1DbXkyMKo&ab_channel=griffpatch

**Comment by Lolorpof** [comment]
**_Collision Code_**
- https://scratch.mit.edu/projects/730593779

**Comment by XSeeGuZ** [comment]
**_Rolling_**
- https://scratch.mit.edu/projects/730567146
