### ISSUE TITLE
ลองทำ demo น้องก้อนวิ่งบนราง

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/cpe103-test-group-15#5]

**Comment by XSeeGuZ** [comment]
ลองประยุกต์ น้องเคลื่อนที่บนรางจากคลิปวิดีโอ
https://youtu.be/YOhpXBV1Yns

**Comment by XSeeGuZ** [comment]
**_น้องวิ่งบนราง_**
https://scratch.mit.edu/projects/730989691
