### ISSUE TITLE
รูปประกอบ 

### ISSUE THREAD

**Issue by bambiiisadeer** [MindIssawara/cpe103-test-group-15#8]
https://drive.google.com/drive/folders/1GGrTqxFaYmgiW4X8jfHipzGNaX9pjGKo

**Comment by bbambiiisadeer** [comment]
![5AF43752-1B9A-4FC4-9C73-3CCF525053FE](https://user-images.githubusercontent.com/110961766/189671938-911e2ee4-8715-4f03-abc5-7e0014993d8d.png)
![71037C80-FB24-4F93-B308-AC4AB1A7EFBC](https://user-images.githubusercontent.com/110961766/189671969-e37f76bd-cc90-4a44-9bbc-89d6978efd6e.png)
![2510B1E0-8465-4D8C-B232-C8E3B6669167](https://user-images.githubusercontent.com/110961766/189671974-35cca813-915e-460d-b49e-302e0660b7cb.png)

**Comment by bambiiisadeer** [comment]
![EDDAF72D-01CF-4F5B-AB6C-760D1A9E4729](https://user-images.githubusercontent.com/110961766/189672089-8d4ab2f6-1026-4a4a-8226-a51b2c46e90a.png)
![B3B246F2-AB9B-4C1E-A7C0-003E114B60EE](https://user-images.githubusercontent.com/110961766/189672118-4dffaa27-a4f7-4282-83ba-00fa08817313.png)
![8C3563C7-225A-41A1-84D3-ACF6304B134D](https://user-images.githubusercontent.com/110961766/189672132-31a3129e-4dbd-4ada-962a-ae713f752609.png)
